version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: pytest
    versions:
    - ">= 0"
  - dependency-name: setuptools
    versions:
    - ">= 0"
  - dependency-name: twine
    versions:
    - ">= 0"
  - dependency-name: wheel
    versions:
    - ">= 0"
  - dependency-name: pollination-dsl
    versions:
    - 0.10.0
    - 0.9.5
    - 0.9.6
    - 0.9.7
  - dependency-name: honeybee-energy
    versions:
    - 1.66.17
    - 1.66.18
    - 1.67.0
    - 1.67.1
    - 1.67.2
    - 1.67.3
    - 1.67.4
    - 1.67.5
    - 1.67.6
    - 1.67.7
    - 1.67.8
  - dependency-name: queenbee-dsl
    versions:
    - 0.7.1
    - 0.7.2
